### ISSUE TITLE
Weird Power Up bug

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#24]
When Claw is powered up (cat nip, magic swords or other thing) if when pick up a new power up game crashes, but when I use Kazam screenrecorder, game works fine 
![image](https://cloud.githubusercontent.com/assets/10581339/25795304/6cee4ca4-33dd-11e7-9468-c3d8cd77e4b5.png)

**Comment by pjasicek** [comment]
Should be fixed with https://github.com/pjasicek/CaptainClaw/commit/d4ba4ca55e412c864e292af89568112fc37b6874

Please check if it is really resolved on Linux, on Windows I have MIDI files playing in seperate process so it behaves a bit differently (the process also crashed previously tho). 

Thanks for the report :)

**Comment by cipiricus** [comment]
So far so good, the game doesn't crash anymore, thanks for the fix :+1:
